- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables #importing the vars to be used in file
      include_vars: vars/vpc_setup
    
    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}" # {{}} is variable sign
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout
    
    - name: create Public Subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub1Cidr }}"
        map_public: yes #should get an IP Id
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

