- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC output Variable
      include_vars: vars/vpc-output_vars

    - name: Import vprofile setup Variable
      include_vars: vars/vprostacksetup

    - name: Import VPC setup Variable
      include_vars: vars/vpc_setup

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: Save private key into file loginkey_vpro.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed
    
    - name: Create Security Group for Load Balancer
      ec2_group:
        name: vproELB-sg
        description: Allow port 80 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules: 
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBSG_out

    - name: Create Security Group for vprofile Stack
      ec2_group:
        name: vproStack-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no #will not recreate rules if not changed
        rules: 
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vproELBSG_out.group_id}}" 

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}" 
      register: vproStackSG_out

    - name: Update Security Group with its own sg id
      ec2_group:
        name: vproStack-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no #if we will not provide this option, the security group will be purged and recreated
        rules:
          - proto: all
            group_id: "{{vproStackSG_out.group_id}}"
    
    - name: Create Nginx web01
      ec2_instance:
        key_name: vprokey
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{nginx_ami}}"
        wait: true #wait until healthcheck is ok
        wait_timeout: 300
        security_group: "{{vproStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
        tags:
          Name: "web01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1 #to make sure we wont create ec2 instance every run
      register: web01_out

    - name: Create tomcat app01
      ec2_instance:
        key_name: vprokey
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{tomcat_ami}}"
        wait: true #wait until healthcheck is ok
        wait_timeout: 300
        security_group: "{{vproStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
        tags:
          Name: "app01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1 #to make sure we wont create ec2 instance every run
      register: app01_out

    - name: Create memcache mc01
      ec2_instance:
        key_name: vprokey
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{memcache_ami}}"
        wait: true #wait until healthcheck is ok
        wait_timeout: 300
        security_group: "{{vproStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
        tags:
          Name: "mc01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1 #to make sure we wont create ec2 instance every run
      register: mc01_out

    - name: Create RabbitMQ mc01
      ec2_instance:
        key_name: vprokey
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{rmq_ami}}"
        wait: true #wait until healthcheck is ok
        wait_timeout: 300
        security_group: "{{vproStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
        tags:
          Name: "rmq01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1 #to make sure we wont create ec2 instance every run
      register: rmq01_out

    - name: Create Mysql db01
      ec2_instance:
        key_name: vprokey
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{mysql_ami}}"
        wait: true #wait until healthcheck is ok
        wait_timeout: 300
        security_group: "{{vproStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
        tags:
          Name: "db01"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1 #to make sure we wont create ec2 instance every run
      register: db01_out

    
    
